name: testproj
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/clock.png
   - images/profile.jpg
  fonts:
  - family: SourceSans
    fonts:
    - asset: fonts/SourceSansPro-Light.ttf
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
